---
title: "Rstudio Work Example"
output:
  distill::distill_article:
    code_folding: true
---

## **Data Visualization**

```{r, echo=FALSE}
library(scales)
d <- read.csv(file = "PS_09_orangutans.csv",
              header = TRUE)


den <- d[ ,c(8,4,6)]
per <- d[ ,c(7,3,5)]
time <- d[ , c(2)]

makeTransparent <- function(black, alpha = my.alpha){
	newColor <- col2rgb(black)
	apply(newColor, 2, function(curcoldata)			
	     {rgb(red   = curcoldata[1],
	          green = curcoldata[2],
	          blue  = curcoldata[3],
	          alpha = alpha,
	          maxColorValue =  255)})
}
my.alpha <- 100


plot.matrix <- matrix(c(1,4,4,
                        2,5,5,
                        3,6,6),
                        nrow = 3, ncol = 3, byrow = TRUE)

layout(mat = plot.matrix)
mar.left   <- c(2, 2, 1.5, 2)
mar.right  <- c(2, 0, 1.5, 4)

col.CIs    <- makeTransparent("gray60")
col.habs <- c("green4","blue3", "darkorange")
tcol.habs = makeTransparent(col.habs)
col.bars   <- makeTransparent("gray60")   
col.bords  <- "gray60"  
axis.cols  <- c("white","white","black")
cex.axis   <- 1.2
cex.labs <- 1.2

size.point <- 1.2                                     
par(oma = c(2,2,1,2))

box.letters <- c("A",
                 "C",
                 "E")

for (i in 1:3) {

par(mar = mar.left)
  
oh    <- den[ , i]
fr    <- per[ , i]*100

plot(oh ~ fr,
     xlim = c(0,1.5),
     ylim = c(0,8),
     type = "n",
     bty = "n",
     axes = FALSE)
m <- lm(oh ~ fr)
xvals <- seq(from = 0, to = 100 , by = 0.01)
df <- data.frame(fr = xvals)
CI <- predict(m, newdata = df, interval = "confidence")
CI <- as.data.frame(CI)
polygon(c(xvals, rev(xvals)),
     c(CI$lwr, rev(CI$upr)),
     col = col.CIs, border = NA)
lines(xvals, CI[, 1], col = "gray60", lwd =  2)

points(oh ~ fr,            
     pch = 16,
     cex = size.point,
     col = tcol.habs[i])

axis (side = 1,                        
      at = c(0,0.5,1,1.5),
      labels = c("0","0.5","1","1.5"),
      col.axis = axis.cols[i],         
      cex.axis = cex.axis,
      las = 1)

axis (side = 2,                        
      at = c(0, 2, 4, 6, 8),
      labels = c("0", "2", "4","6","8"), 
      cex.axis = cex.axis,
      las = 1,
      col = col.habs[i],
      col.axis = col.habs[i])

text (0, 7.5,                          
      labels = box.letters[i], 
      pos = 4,
      offset = -0.00000001,
      col = "black",
      cex = cex.labs)
}

mtext (side = 2, text = "Population density (individuals/km2) ",
       outer = TRUE, cex = 0.8, line = 0.5)
mtext (side = 1, text = "% stems with M/R fruit ",
       outer = FALSE, cex = 0.8, line = 2)


box.letters2 <- c("B",
                  "D",
                  "F")

box.letters3 <- c("Montane",
                  "Lowlands",
                  "Peat swamp")

for (i in 1:3) {

par(mar = mar.right)
oh <- den[, i]
fr <- per[, i]*100


barplot(fr,
        axes = FALSE,       
        bty = 'n',
        ylim = c (0, 1.5),
        border = col.bords,
        col = col.bars)

par(new = TRUE)
plot(oh ~ time,
     axes = FALSE,
     bty = 'n',
     ylim = c(0, 8),     
     type = 'l', 
     pch = 16,
     cex = size.point,
     col = col.habs[i])
abline(h=mean(oh),
      lty = 2,
      col = col.habs[i])

axis (side = 4,                        
      at = c(0, 8/3, 16/3 , 8),
      labels = c("0","0.5","1","1.5"),
      col = col.bars,
      col.axis = "gray40",         
      cex.axis = cex.axis,
      las = 1)

axis (side = 1,                        
      at = c(time[4], time[15], time[27]),
      labels = c("Jan 2008", "Jan 2009", "Jan 2010"), 
      cex.axis = cex.axis,
      las = 1,
      col = axis.cols[i],
      col.axis = axis.cols[i])

axis (side = 2,                        
      at = c(0, 2, 4, 6, 8),
      labels = c("","","","",""),
      col = col.habs[i],
      col.axis = col.habs[i],
      las = 1)

text (0, 7.5,                          
      labels = box.letters2[i], 
      pos = 4,
      col = "black",
      cex = cex.labs)

text (time[15], 7.5,                          
      labels = box.letters3[i], 
      pos = 4,
      col = col.habs[i],
      cex = cex.labs)

}

mtext (side = 4, text = "% stems with mature or ripe fruit ",
       outer = TRUE, cex = 0.8, line = 0, col = "gray40")
```




```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

